services:
  zwaar_app:
    image: node:14-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: npm run dev
    ports:
      - "32769:32769"
    environment:
      - NODE_ENV=development
      - PORT=32769
      - HOST=0.0.0.0